openapi: 3.0.3
info:
  title: API Category extension
  version: 4.0.0
tags:
  - name: categoryExtension
security:
  - bearerAuth: []
paths:
  /category/{id}:
    put:
      operationId: createCategoryWithId
      tags: [categoryExtension]
      parameters:
        - name: id
          required: true
          in: path
          schema: { type: string }
      requestBody:
        required: true
        content:
          application/json;charset=utf-8:
            schema: { $ref: '#/components/schemas/Category_Create' }
      responses:
        '201':
          description: Created
          content:
            application/json;charset=utf-8:
              schema: { $ref: '#/components/schemas/Category' }
        '400': { description: Bad Request }
        '401': { description: Unauthorized }
        '403': { description: Forbidden }
        '405': { description: Method Not Allowed }
        '409': { description: Conflict }
        '500': { description: Internal Server Error }
components:
  schemas:
    Category:
      type: object
      properties:
        id: { type: string }
    Category_Create:
      type: object
      properties:
        name: { type: string }
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
