openapi: 3.0.3
info:
  title: API ProductOrder extension
  version: 4.0.0
tags:
  - name: productOrderExtension
paths:
  /productOrder/{id}:
    put:
      operationId: createProductOrderWithId
      tags: [productOrderExtension]
      parameters:
        - name: id
          required: true
          in: path
          schema: { type: string }
      requestBody:
        required: true
        content:
          application/json;charset=utf-8:
            schema: { $ref: '#/components/schemas/ProductOrder_Create' }
      responses:
        '201':
          description: Created
          content:
            application/json;charset=utf-8:
              schema: { $ref: '#/components/schemas/ProductOrder' }
        '400': { description: Bad Request }
        '401': { description: Unauthorized }
        '403': { description: Forbidden }
        '405': { description: Method Not Allowed }
        '409': { description: Conflict }
        '500': { description: Internal Server Error }
components:
  schemas:
    ProductOrder:
      type: object
      properties:
        id: { type: string }
    ProductOrder_Create:
      type: object
      properties:
        description: { type: string }
