package org.fiware.tmforum.common.mapping;


import io.github.wistefan.mapping.annotations.MappingEnabled;
import org.mapstruct.Context;
import org.mapstruct.Named;

import java.net.URI;
import java.util.Arrays;
import java.util.List;
import java.util.Optional;
import java.util.UUID;
import java.util.regex.Pattern;

import static org.fiware.tmforum.common.CommonConstants.ID_TEMPLATE;

@Named("IdHelper")
public class IdHelper {

	private final static Pattern NGSI_LD_URN_PATTERN = Pattern.compile(
			"^urn:ngsi-ld:[a-z0-9-]{0,31}:([a-z0-9()+,\\-.:=@;$_!*']|%[0-9a-f]{2})+$",
			Pattern.CASE_INSENSITIVE);

	/**
	 * Check if the given id is NGSI-LD compliant.
	 *
	 * @param id the id to check
	 * @return true if its NGSI-LD compliant
	 */
	public static boolean isNgsiLdId(String id) {
		return Optional.ofNullable(id)
				.filter(nonNullId -> NGSI_LD_URN_PATTERN.matcher(nonNullId).matches())
				.isPresent();
	}

	/**
	 * Check if the given id is NGSI-LD compliant AND its type segment matches the
	 * entity type declared via {@link MappingEnabled} on the given class. This is required
	 * when the id originates from a caller (e.g. PUT with a custom id) instead of being
	 * generated by {@link #toNgsiLd(String, String)}, since in that case the type segment
	 * is not otherwise guaranteed to be correct.
	 *
	 * @param id          the id to check
	 * @param entityClass the domain class the id is intended for
	 * @return true if the id is NGSI-LD compliant and of the expected type
	 */
	public static boolean isNgsiLdId(String id, Class<?> entityClass) {
		if (!isNgsiLdId(id)) {
			return false;
		}
		MappingEnabled mappingAnnotation = entityClass.getAnnotation(MappingEnabled.class);
		if (mappingAnnotation == null) {
			throw new IllegalArgumentException(
					String.format("Class %s missing @MappingEnabled annotation", entityClass.getName()));
		}
		String requestedType = id.split(":", 4)[2];
		return Arrays.asList(mappingAnnotation.entityType()).contains(requestedType);
	}

	/**
	 * Create an NGSI-LD compliant id
	 *
	 * @param id         id to be translated
	 * @param targetType entity type
	 * @return the compliant id
	 */
	@Named("ToNgsiLd")
	public static URI toNgsiLd(String id, @Context String targetType) {
		return URI.create(String.format(ID_TEMPLATE, targetType, Optional.ofNullable(id).orElse(UUID.randomUUID().toString())));
	}

	/**
	 * Extract the id part from the NGSI-LD id
	 *
	 * @param id the full id
	 * @return only the id part
	 */
	@Named("FromNgsiLd")
	public static String fromNgsiLd(URI id) {
		return Optional.ofNullable(id)
				.map(URI::toString)
				.filter(IdHelper::isNgsiLdId)
				.map(stringId -> id.toString().split(":"))
				.map(stringArray -> stringArray[stringArray.length - 1])
				.orElseThrow(() -> new RuntimeException(String.format("Did not receive a valid uri: %s", id)));
	}

	@Named("NullableListMapper")
	public static <T> List<T> nullableListMapper(List<T> theNullableList) {
		return theNullableList;
	}
}
