name: Conformance Test

on:
  push

jobs:
  conformance:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        module: [party]

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-java@v1
        with:
          java-version: '17'
          java-package: jdk

      - name: Compile
        run: |
          mvn clean package
        

      - name: Execute tests
        id: test
        run: |
          cd ${{matrix.module}}
          mvn test integration-test -Pconformance-test

      - name: Collect results
        shell: bash
        run: |
          if $(cat target/jsonResults.json | jq '.run.failures') == [] then
            exit 0
          elif
            cat target/jsonResults.json
            exit 1
          fi